# Generated by Django 3.0.7 on 2020-06-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='our_user',
        ),
    ]
