# Generated by Django 3.0.7 on 2020-06-22 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillbot', '0003_our_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 22, 13, 39, 37, 729348)),
            preserve_default=False,
        ),
    ]
