# Generated by Django 3.0.7 on 2020-06-22 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillbot', '0004_our_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_user',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 44, 31, 765328)),
        ),
    ]
