# Generated by Django 3.0.7 on 2020-06-22 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillbot', '0005_our_user_date_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_user',
            name='date_made1',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 49, 51, 924814)),
        ),
        migrations.AlterField(
            model_name='our_user',
            name='date_made',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 49, 51, 924814)),
        ),
    ]
